require("dotenv").config();
const bcrypt = require("bcrypt"); const pool = require("../db");
const password = "Test@123";
const sellers = ["Tech Bazaar","Gadget Hub","Urban Style","Home Comfort","Time & Carry"];
const drivers = [["Rahim Ahmed","delivery1@example.com","01710000001","Dhaka",23.8103,90.4125],["Karim Hasan","delivery2@example.com","01710000002","Rangpur",25.7439,89.2752],["Sakib Hossain","delivery3@example.com","01710000003","Rajshahi",24.3745,88.6042],["Tanvir Islam","delivery4@example.com","01710000004","Chittagong",22.3569,91.7832],["Fahim Rahman","delivery5@example.com","01710000005","Sylhet",24.8949,91.8687]];
const categories=["Electronics","Mobile Phones","Computers","Accessories","Fashion","Shoes","Bags","Watches","Home & Kitchen"];
const products=["Samsung Galaxy Smartphone","Wireless Bluetooth Headphones","Gaming Laptop","Mechanical Keyboard","Running Shoes","Leather Backpack","Smart Watch","DSLR Camera","Cotton T-Shirt","Coffee Maker","USB-C Charger","Portable Speaker","Office Chair","Air Fryer","Classic Sneakers","Travel Duffel Bag","Fitness Tracker","Wireless Mouse","4K Monitor","Phone Case","Denim Jacket","Kitchen Blender","Noise Cancelling Earbuds","Laptop Stand","Analog Watch","Canvas Backpack","Smart LED Bulb","Gaming Controller","Ceramic Dinner Set","Formal Shoes"];
async function account(table,id,name,email,phone,extra={}) { const found=await pool.query(`SELECT ${id} id FROM ${table} WHERE email=$1`,[email]); if(found.rowCount)return found.rows[0].id; const hash=await bcrypt.hash(password,12); const fields=table==="deliverymen"?"name,email,phone,password,delivery_location,delivery_latitude,delivery_longitude,approval_status,availability_status":table==="sellers"?"name,email,phone,password,approval_status":"name,email,phone,password"; const vals=table==="deliverymen"?[name,email,phone,hash,extra.location,extra.lat,extra.lng,"approved","available"]:table==="sellers"?[name,email,phone,hash,"approved"]:[name,email,phone,hash]; const marks=vals.map((_,i)=>`$${i+1}`).join(","); const r=await pool.query(`INSERT INTO ${table} (${fields}) VALUES (${marks}) RETURNING ${id} id`,vals); return r.rows[0].id; }
async function main(){const sellerIds=[];for(let i=0;i<5;i++)sellerIds.push(await account("sellers","seller_id",sellers[i],`seller${i+1}@example.com`,`0181000000${i+1}`));const driverIds=[];for(const d of drivers)driverIds.push(await account("deliverymen","deliveryman_id",d[0],d[1],d[2],{location:d[3],lat:d[4],lng:d[5]}));const customerIds=[];for(let i=1;i<=8;i++)customerIds.push(await account("customers","customer_id",`Test Customer ${i}`,`customer${i}@example.com`,`0191000000${i}`));const catIds={};for(const name of categories){const r=await pool.query("INSERT INTO categories (category_name) VALUES ($1) ON CONFLICT (category_name) DO UPDATE SET category_name=EXCLUDED.category_name RETURNING category_id",[name]);catIds[name]=r.rows[0].category_id;}for(let i=0;i<products.length;i++){const seller=sellerIds[i%5], category=catIds[categories[i%categories.length]], name=products[i];const exists=await pool.query("SELECT product_id FROM products WHERE name=$1 AND seller_id=$2",[name,seller]);if(!exists.rowCount)await pool.query("INSERT INTO products (name,description,price,stock,image,seller_id,category_id) VALUES ($1,$2,$3,$4,$5,$6,$7)",[name,`Seeded realistic ${name.toLowerCase()} for delivery-system testing.`,1000+i*250,20+i,`https://images.unsplash.com/photo-${i%2?"1511707171634-5f897ff02aa9":"1496181133206-80ce9b88a853"}?auto=format&fit=crop&w=800&q=80`,seller,category]);}
const locations=["Seed delivery: Dhaka","Seed delivery: Rangpur","Seed delivery: Sylhet"];
const oldOrders=await pool.query("SELECT order_id FROM orders WHERE shipping_address = ANY($1::TEXT[])",[locations]);
if(oldOrders.rowCount){const ids=oldOrders.rows.map(row=>row.order_id);await pool.query("DELETE FROM delivery_messages WHERE order_id = ANY($1::BIGINT[])",[ids]);await pool.query("DELETE FROM delivery_requests WHERE order_id = ANY($1::BIGINT[])",[ids]);await pool.query("DELETE FROM order_items WHERE order_id = ANY($1::BIGINT[])",[ids]);await pool.query("DELETE FROM orders WHERE order_id = ANY($1::BIGINT[])",[ids]);}
await pool.query(`UPDATE deliverymen d
  SET approval_status='approved', availability_status=CASE WHEN EXISTS (
    SELECT 1 FROM orders o WHERE o.deliveryman_id=d.deliveryman_id
      AND o.delivery_status IN ('assigned','picked_up','out_for_delivery')
  ) THEN 'busy' ELSE 'available' END
  WHERE d.email = ANY($1::TEXT[])`,[drivers.map(d=>d[1])]);
console.log("Delivery demo seed complete with zero seeded orders. Password for all seeded accounts: Test@123");}
main().catch(e=>{console.error("Delivery demo seed failed:",e);process.exitCode=1;}).finally(()=>pool.end());
